project:
  type: website

website:
  title: "Sarah Webb"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: research.qmd
      - text: "CV"
        href: Webb_CV_Sept25.pdf

